---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: docker:latest
    commands:
      - docker build -t $IMAGE_NAME:$DRONE_COMMIT_BRANCH-$DRONE_COMMIT_SHA -t $IMAGE_NAME:$DRONE_COMMIT_BRANCH .
      - docker images
    environment:
      IMAGE_NAME: orlandobrea/api 

