---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: precheck
    image: orlandobrea/andes-check-image-exist:latest
    pull: always
    environment:
      REGISTRY_URL: registry.192-168-68-2.nip.io:30443
      IMAGE: andes/api
      TAG: ${DRONE_BRANCH}-${DRONE_COMMIT_SHA}
  - name: build
    image: plugins/docker  
    when:
      status:
        - failure    
    settings:
      debug: true
      username: 
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      registry: registry.192-168-68-2.nip.io:30443
      repo: registry.192-168-68-2.nip.io:30443/andes/api
      tags: ["${DRONE_BRANCH}", "${DRONE_BRANCH}-${DRONE_COMMIT_SHA}"]
      insecure: true
