---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: plugins/docker  
    settings:
      debug: true
      username: admin
      password: admin
      registry: docker-registry.192-168-0-8.nip.io:30443
      repo: docker-registry.192-168-0-8.nip.io:30443/orlandobrea/api
      tags: ["${DRONE_BRANCH}", "${DRONE_BRANCH}-${DRONE_COMMIT_SHA}"]
      insecure: true
    # commands:
    #   - docker build -t $IMAGE_NAME:$DRONE_COMMIT_BRANCH-$DRONE_COMMIT_SHA -t $IMAGE_NAME:$DRONE_COMMIT_BRANCH .
    #   - docker images

